apiVersion: v1
kind: Service
metadata:
  name: kafka-service-image-zvarich
spec:
  selector:
    app: kafka-image-zvarich
  ports:
  - port: 80 #external(exposed)
    targetPort: 5000 #internal
  type: NodePort
